# Covid Forecasting - Data Collection and Cleaning

## Import Libraries and Initialize Constants

In [1]:
from dotenv import load_dotenv
import os
import pandas as pd
import requests
import time

load_dotenv()

BASE_URL_COVIDCAST = "https://api.covidcast.cmu.edu/epidata/api.php" # CovidCast endpoint
BASE_URL_HOSPITALIZATION = "https://api.delphi.cmu.edu/epidata/covid_hosp_state_timeseries/" # Covid Hospitalization endpoint

# 50 states + DC (careful of usage limits)
STATES_COVIDCAST = [
    "al","ak","az","ar","ca","co","ct","de","fl","ga",
    "hi","id","il","in","ia","ks","ky","la","me","md",
    "ma","mi","mn","ms","mo","mt","ne","nv","nh","nj",
    "nm","ny","nc","nd","oh","ok","or","pa","ri","sc",
    "sd","tn","tx","ut","vt","va","wa","wv","wi","wy","dc"
]

HEADER = {"user-agent": os.getenv("USER_AGENT", "CovidCasesExplorer/1.0")}

STATES_HOSPITALIZATION = [s.upper() for s in STATES_COVIDCAST] # needs to be upper case for the hospitalization API

START_DATE = "20200101"
END_DATE = "20251231"

NA_THRESHOLD = 0.9 # if a feature has too many NA's then it will not be useful

## Create Data Dictionary

In [2]:
# This dictionary is a reference for what each feature in the CovidCast data means.
covid_cast_data_dictionary = {
    "fb-survey_smoothed_wwearing_mask_7d": """Estimated percentage of people who wore a mask for most or all of the time while in public in the past 7 days; those not in public in the past 7 days are not counted.""",
    "fb-survey_smoothed_wcovid_vaccinated_appointment_or_accept": """Estimated percentage of respondents who either have already received a COVID vaccine or have an appointment to get a COVID vaccine or would definitely or probably choose to get vaccinated, if a vaccine were offered to them today.""",
    "google-symptoms_sum_anosmia_ageusia_smoothed_search": """The sum of Google search volume for anosmia and ageusia related searches, in an arbitrary units that are normalized for overall search users, smoothed by 7-day average""",
    "fb-survey_smoothed_wcli": """Estimated percentage of people with COVID-like illness""",
    "fb-survey_smoothed_whh_cmnty_cli": "Estimated percentage of people reporting illness in their local community, as described below, including their household",
    "doctor-visits_smoothed_adj_cli": """Estimated percentage of outpatient doctor visits primarily about COVID-related symptoms, based on data from health system partners, smoothed in time using a Gaussian linear smoother""",
    "jhu-csse_confirmed_incidence_num": """Number of new confirmed COVID-19 cases, daily""",
    "hhs_confirmed_admissions_covid_1d_prop_7dav": """Sum of Adult + Pediatric. Confirmed admissions only.""",
    "jhu-csse_deaths_7dav_incidence_prop": """Number of new confirmed deaths due to COVID-19 per 100,000 population, daily""",
    "chng_smoothed_adj_outpatient_covid": """Estimated percentage of outpatient doctor visits with confirmed COVID-19, based on Change Healthcare claims data that has been de-identified in accordance with HIPAA privacy regulations, smoothed in time using a Gaussian linear smoother""",
    "chng_7dav_inpatient_covid": """Ratio of inpatient hospitalizations associated with COVID-19, based on Change Healthcare claims data that has been de-identified in accordance with HIPAA privacy regulations, smoothed in time with a trailing 7 day average. This historical signal is no longer updated."""
}

In [3]:
pd.set_option('display.max_colwidth', None) # helps for displaying long text

covid_cast_definitions_df = pd.DataFrame(data = {
    "Metric": covid_cast_data_dictionary.keys(),
    "Definition": covid_cast_data_dictionary.values()
})

covid_cast_definitions_df

,Metric,Definition
0,fb-survey_smoothed_wwearing_mask_7d,Estimated percentage of people who wore a mask for most or all of the time while in public in the past 7 days; those not in public in the past 7 days are not counted.
1,fb-survey_smoothed_wcovid_vaccinated_appointment_or_accept,"Estimated percentage of respondents who either have already received a COVID vaccine or have an appointment to get a COVID vaccine or would definitely or probably choose to get vaccinated, if a vaccine were offered to them today."
2,google-symptoms_sum_anosmia_ageusia_smoothed_search,"The sum of Google search volume for anosmia and ageusia related searches, in an arbitrary units that are normalized for overall search users, smoothed by 7-day average"
3,fb-survey_smoothed_wcli,Estimated percentage of people with COVID-like illness
4,fb-survey_smoothed_whh_cmnty_cli,"Estimated percentage of people reporting illness in their local community, as described below, including their household"
5,doctor-visits_smoothed_adj_cli,"Estimated percentage of outpatient doctor visits primarily about COVID-related symptoms, based on data from health system partners, smoothed in time using a Gaussian linear smoother"
6,jhu-csse_confirmed_incidence_num,"Number of new confirmed COVID-19 cases, daily"
7,hhs_confirmed_admissions_covid_1d_prop_7dav,Sum of Adult + Pediatric. Confirmed admissions only.
8,jhu-csse_deaths_7dav_incidence_prop,"Number of new confirmed deaths due to COVID-19 per 100,000 population, daily"
9,chng_smoothed_adj_outpatient_covid,"Estimated percentage of outpatient doctor visits with confirmed COVID-19, based on Change Healthcare claims data that has been de-identified in accordance with HIPAA privacy regulations, smoothed in time using a Gaussian linear smoother"
10,chng_7dav_inpatient_covid,"Ratio of inpatient hospitalizations associated with COVID-19, based on Change Healthcare claims data that has been de-identified in accordance with HIPAA privacy regulations, smoothed in time with a trailing 7 day average. This historical signal is no longer updated."

## Define Functions for API Calls

In [4]:
# Functions for CovidCast Endpoint

def fetch_signal_state_covidcast(data_source, signal, state, use_api_key):
    params = {
        "source": "covidcast",
        "data_source": data_source,
        "signal": signal,
        "time_type": "day",
        "geo_type": "state",
        "geo_value": state,
        "time_values": f"{START_DATE}-{END_DATE}"
    }

    if use_api_key:
        params["api_key"] = os.getenv("API_KEY")

    r = requests.get(BASE_URL_COVIDCAST, params=params, headers=HEADER, timeout=30)

    if r.status_code == 200:
        data = r.json()
        if data.get("result") != 1:
            print(f"API error {state}:", data.get("message"))
            return None

        df = pd.DataFrame(data["epidata"])
        if df.empty:
            return None

        df = df[["time_value", "geo_value", "value"]]

        df = df.rename(columns={
            "geo_value": "geo",
            "value": f"{data_source}_{signal}"
        })

        # rename to match Hospitalization data
        df = df.rename(columns={
            "geo": "state", 
            "time_value": "date"
        })

        df["state"] = df["state"].str.upper() # upper case to match Hospitalization data

        return df

    else:
        print(f"HTTP {r.status_code} for {state}")
        return None


def fetch_all_states_covidcast(source, signal, use_api_key=False):
    """
    Fetch data for all states from a given source and signal.
    """
    dfs = []

    print(f"Fetching '{signal}' from '{source}' for {len(STATES_COVIDCAST)} states...")

    for state in STATES_COVIDCAST:  # lowercase for API
        try:
            df = fetch_signal_state_covidcast(source, signal, state, use_api_key)
            if df is not None and not df.empty:
                dfs.append(df)
            else:
                print(f"  ⚠ No data for state: {state}")
        except Exception as e:
            print(f"  ❌ Error fetching state {state}: {e}")

        time.sleep(0.5)  # avoid 429 rate-limit errors

    if dfs:
        result = pd.concat(dfs, ignore_index=True)
        print(f"✅ Successfully fetched data for {len(dfs)} states.")
        return result
    else:
        print("⚠ No data fetched from any state. Returning empty DataFrame.")
        return pd.DataFrame()

In [5]:
# Functions for Hospitalization Endpoint

def fetch_signal_state_hospitalization(state, use_api_key):

    params = {
        "states": state,
        "dates": f"{START_DATE}-{END_DATE}"
    }

    if use_api_key:
        params["api_key"] = os.getenv("API_KEY")

    r = requests.get(BASE_URL_HOSPITALIZATION, params=params, headers=HEADER, timeout=30)

    if r.status_code == 200:
        data = r.json()
        if data.get("result") != 1:
            print(f"API error {state}:", data.get("message"))
            return None

        df = pd.DataFrame(data["epidata"])
        if df.empty:
            return None

        return df

    else:
        print(f"HTTP {r.status_code} for {state}")
        return None


def fetch_all_states_covidcast_hospitalization(use_api_key=False):
    """
    Fetch data for all states from a given source and signal.
    """
    dfs = []

    print(f"Fetching Hospitalization data from covid_hosp_state_timeseries for {len(STATES_HOSPITALIZATION)} states...")

    for state in STATES_HOSPITALIZATION:  # lowercase for API
        try:
            df = fetch_signal_state_hospitalization(state, use_api_key)
            if df is not None and not df.empty:
                dfs.append(df)
            else:
                print(f"  ⚠ No data for state: {state}")
        except Exception as e:
            print(f"  ❌ Error fetching state {state}: {e}")

        time.sleep(0.5)  # avoid 429 rate-limit errors

    if dfs:
        result = pd.concat(dfs, ignore_index=True)
        print(f"✅ Successfully fetched data for {len(dfs)} states.")
        return result
    else:
        print("⚠ No data fetched from any state. Returning empty DataFrame.")
        return pd.DataFrame()

## Data Collection

In [6]:
# CovidCast
masks = fetch_all_states_covidcast("fb-survey", "smoothed_wwearing_mask_7d", use_api_key=True)
vaccine_acceptance = fetch_all_states_covidcast("fb-survey", "smoothed_wcovid_vaccinated_appointment_or_accept", use_api_key=True)
searches = fetch_all_states_covidcast("google-symptoms", "sum_anosmia_ageusia_smoothed_search", use_api_key=True)
symptoms = fetch_all_states_covidcast("fb-survey", "smoothed_wcli", use_api_key=True)
community_symptoms = fetch_all_states_covidcast("fb-survey", "smoothed_whh_cmnty_cli", use_api_key=True)
doctor_visits = fetch_all_states_covidcast("doctor-visits", "smoothed_adj_cli", use_api_key=True)
cases = fetch_all_states_covidcast("jhu-csse", "confirmed_incidence_num", use_api_key=True)
admissions = fetch_all_states_covidcast("hhs", "confirmed_admissions_covid_1d_prop_7dav", use_api_key=True)
deaths = fetch_all_states_covidcast("jhu-csse", "deaths_7dav_incidence_prop", use_api_key=True)
outpatient = fetch_all_states_covidcast("chng", "smoothed_adj_outpatient_covid", use_api_key=True)
inpatient = fetch_all_states_covidcast("chng", "7dav_inpatient_covid", use_api_key=True)

Fetching 'smoothed_wwearing_mask_7d' from 'fb-survey' for 51 states...
✅ Successfully fetched data for 51 states.
Fetching 'smoothed_wcovid_vaccinated_appointment_or_accept' from 'fb-survey' for 51 states...
✅ Successfully fetched data for 51 states.
Fetching 'sum_anosmia_ageusia_smoothed_search' from 'google-symptoms' for 51 states...
API error ak: no results
  ⚠ No data for state: ak
API error de: no results
  ⚠ No data for state: de
API error mt: no results
  ⚠ No data for state: mt
API error nd: no results
  ⚠ No data for state: nd
API error sd: no results
  ⚠ No data for state: sd
API error vt: no results
  ⚠ No data for state: vt
API error wy: no results
  ⚠ No data for state: wy
✅ Successfully fetched data for 44 states.
Fetching 'smoothed_wcli' from 'fb-survey' for 51 states...
✅ Successfully fetched data for 51 states.
Fetching 'smoothed_whh_cmnty_cli' from 'fb-survey' for 51 states...
✅ Successfully fetched data for 51 states.
Fetching 'smoothed_adj_cli' from 'doctor-visits' for 51 states...
✅ Successfully fetched data for 51 states.
Fetching 'confirmed_incidence_num' from 'jhu-csse' for 51 states...
✅ Successfully fetched data for 51 states.
Fetching 'confirmed_admissions_covid_1d_prop_7dav' from 'hhs' for 51 states...
✅ Successfully fetched data for 51 states.
Fetching 'deaths_7dav_incidence_prop' from 'jhu-csse' for 51 states...
✅ Successfully fetched data for 51 states.
Fetching 'smoothed_adj_outpatient_covid' from 'chng' for 51 states...
✅ Successfully fetched data for 51 states.
Fetching '7dav_inpatient_covid' from 'chng' for 51 states...
✅ Successfully fetched data for 51 states.

In [7]:
# Hospitalization
hospitalization = fetch_all_states_covidcast_hospitalization(use_api_key=True)

Fetching Hospitalization data from covid_hosp_state_timeseries for 51 states...
✅ Successfully fetched data for 51 states.

## Data Cleaning

In [8]:
# ----------------------------
# MERGE
# ----------------------------

features = [
    masks,
    vaccine_acceptance,
    searches,
    symptoms,
    community_symptoms,
    doctor_visits,
    cases,
    admissions,
    deaths,
    outpatient,
    inpatient,
    hospitalization
]

df = features[0]

for f in (features[1:]):
    df = df.merge(f, on=["date","state"], how="outer")

df["date"] = pd.to_datetime(df["date"], format="%Y%m%d")

# Drop columns with too many NA's
df = df.drop(columns = ["geocoded_state", "total_patients_hospitalized_confirmed_influenza_covid", "total_patients_hospitalized_confirmed_influenza_covid_coverage"]) 

df = df.sort_values(["state","date"])

## Feature Engineering

In [9]:
# ----------------------------
# FEATURE ENGINEERING
# ----------------------------

TARGET = "jhu-csse_confirmed_incidence_num"

# Rolling mean
df["cases_roll_7"] = (
    df.groupby("state")[TARGET]
      .transform(lambda x: x.rolling(7).mean())
)

# Seasonality
df["day_of_year"] = df["date"].dt.dayofyear
df["day_of_week"] = df["date"].dt.dayofweek
df["month_of_year"] = df["date"].dt.month
df["quarter_of_year"] = df["date"].dt.quarter

print("Final shape:", df.shape)

Final shape: (111792, 131)

## Quick EDA (Majority Will Be Done in Tableau)

In [10]:
print("Number of Features:", len(df.columns))

Number of Features: 131

In [11]:
df.columns.sort_values().values

array(['adult_icu_bed_covid_utilization',
       'adult_icu_bed_covid_utilization_coverage',
       'adult_icu_bed_covid_utilization_denominator',
       'adult_icu_bed_covid_utilization_numerator',
       'adult_icu_bed_utilization', 'adult_icu_bed_utilization_coverage',
       'adult_icu_bed_utilization_denominator',
       'adult_icu_bed_utilization_numerator', 'cases_roll_7',
       'chng_7dav_inpatient_covid', 'chng_smoothed_adj_outpatient_covid',
       'critical_staffing_shortage_anticipated_within_week_no',
       'critical_staffing_shortage_anticipated_within_week_not_reported',
       'critical_staffing_shortage_anticipated_within_week_yes',
       'critical_staffing_shortage_today_no',
       'critical_staffing_shortage_today_not_reported',
       'critical_staffing_shortage_today_yes', 'date', 'day_of_week',
       'day_of_year', 'deaths_covid', 'deaths_covid_coverage',
       'doctor-visits_smoothed_adj_cli', 'fb-survey_smoothed_wcli',
       'fb-survey_smoothed_wcovid_vaccinated_appointment_or_accept',
       'fb-survey_smoothed_whh_cmnty_cli',
       'fb-survey_smoothed_wwearing_mask_7d',
       'google-symptoms_sum_anosmia_ageusia_smoothed_search',
       'hhs_confirmed_admissions_covid_1d_prop_7dav',
       'hospital_onset_covid', 'hospital_onset_covid_coverage',
       'icu_patients_confirmed_influenza',
       'icu_patients_confirmed_influenza_coverage',
       'inpatient_bed_covid_utilization',
       'inpatient_bed_covid_utilization_coverage',
       'inpatient_bed_covid_utilization_denominator',
       'inpatient_bed_covid_utilization_numerator', 'inpatient_beds',
       'inpatient_beds_coverage', 'inpatient_beds_used',
       'inpatient_beds_used_coverage', 'inpatient_beds_used_covid',
       'inpatient_beds_used_covid_coverage', 'inpatient_beds_utilization',
       'inpatient_beds_utilization_coverage',
       'inpatient_beds_utilization_denominator',
       'inpatient_beds_utilization_numerator', 'issue',
       'jhu-csse_confirmed_incidence_num',
       'jhu-csse_deaths_7dav_incidence_prop', 'month_of_year',
       'on_hand_supply_therapeutic_a_casirivimab_imdevimab_courses',
       'on_hand_supply_therapeutic_b_bamlanivimab_courses',
       'on_hand_supply_therapeutic_c_bamlanivimab_etesevimab_courses',
       'percent_of_inpatients_with_covid',
       'percent_of_inpatients_with_covid_coverage',
       'percent_of_inpatients_with_covid_denominator',
       'percent_of_inpatients_with_covid_numerator',
       'previous_day_admission_adult_covid_confirmed',
       'previous_day_admission_adult_covid_confirmed_18_19',
       'previous_day_admission_adult_covid_confirmed_18_19_coverage',
       'previous_day_admission_adult_covid_confirmed_20_29',
       'previous_day_admission_adult_covid_confirmed_20_29_coverage',
       'previous_day_admission_adult_covid_confirmed_30_39',
       'previous_day_admission_adult_covid_confirmed_30_39_coverage',
       'previous_day_admission_adult_covid_confirmed_40_49',
       'previous_day_admission_adult_covid_confirmed_40_49_coverage',
       'previous_day_admission_adult_covid_confirmed_50_59',
       'previous_day_admission_adult_covid_confirmed_50_59_coverage',
       'previous_day_admission_adult_covid_confirmed_60_69',
       'previous_day_admission_adult_covid_confirmed_60_69_coverage',
       'previous_day_admission_adult_covid_confirmed_70_79',
       'previous_day_admission_adult_covid_confirmed_70_79_coverage',
       'previous_day_admission_adult_covid_confirmed_80plus',
       'previous_day_admission_adult_covid_confirmed_80plus_coverage',
       'previous_day_admission_adult_covid_confirmed_coverage',
       'previous_day_admission_adult_covid_confirmed_unknown',
       'previous_day_admission_adult_covid_confirmed_unknown_coverage',
       'previous_day_admission_adult_covid_suspected',
       'previous_day_admission_adult_covid_suspected_18_19',
       'previous_day_admission_adult_covid_suspected_18_19_coverage',
       'previous_day_admission_adult_covid_suspected_20_29',
       'previous_day_admission_adult_covid_suspected_20_29_coverage',
       'previous_day_admission_adult_covid_suspected_30_39',
       'previous_day_admission_adult_covid_suspected_30_39_coverage',
       'previous_day_admission_adult_covid_suspected_40_49',
       'previous_day_admission_adult_covid_suspected_40_49_coverage',
       'previous_day_admission_adult_covid_suspected_50_59',
       'previous_day_admission_adult_covid_suspected_50_59_coverage',
       'previous_day_admission_adult_covid_suspected_60_69',
       'previous_day_admission_adult_covid_suspected_60_69_coverage',
       'previous_day_admission_adult_covid_suspected_70_79',
       'previous_day_admission_adult_covid_suspected_70_79_coverage',
       'previous_day_admission_adult_covid_suspected_80plus',
       'previous_day_admission_adult_covid_suspected_80plus_coverage',
       'previous_day_admission_adult_covid_suspected_coverage',
       'previous_day_admission_adult_covid_suspected_unknown',
       'previous_day_admission_adult_covid_suspected_unknown_coverage',
       'previous_day_admission_influenza_confirmed',
       'previous_day_admission_influenza_confirmed_coverage',
       'previous_day_admission_pediatric_covid_confirmed',
       'previous_day_admission_pediatric_covid_confirmed_coverage',
       'previous_day_admission_pediatric_covid_suspected',
       'previous_day_admission_pediatric_covid_suspected_coverage',
       'previous_day_deaths_covid_and_influenza',
       'previous_day_deaths_covid_and_influenza_coverage',
       'previous_day_deaths_influenza',
       'previous_day_deaths_influenza_coverage',
       'previous_week_therapeutic_a_casirivimab_imdevimab_courses_used',
       'previous_week_therapeutic_b_bamlanivimab_courses_used',
       'previous_week_therapeutic_c_bamlanivimab_etesevimab_courses_used',
       'quarter_of_year', 'staffed_adult_icu_bed_occupancy',
       'staffed_adult_icu_bed_occupancy_coverage',
       'staffed_icu_adult_patients_confirmed_covid',
       'staffed_icu_adult_patients_confirmed_covid_coverage',
       'staffed_icu_adult_patients_confirmed_suspected_covid',
       'staffed_icu_adult_patients_confirmed_suspected_covid_coverage',
       'state', 'total_adult_patients_hosp_confirmed_covid',
       'total_adult_patients_hosp_confirmed_covid_coverage',
       'total_adult_patients_hosp_confirmed_suspected_covid',
       'total_adult_patients_hosp_confirmed_suspected_covid_coverage',
       'total_patients_hospitalized_confirmed_influenza',
       'total_patients_hospitalized_confirmed_influenza_coverage',
       'total_pediatric_patients_hosp_confirmed_covid',
       'total_pediatric_patients_hosp_confirmed_covid_coverage',
       'total_pediatric_patients_hosp_confirmed_suspected_covid',
       'total_pediatric_patients_hosp_confirmed_suspected_covid_coverage',
       'total_staffed_adult_icu_beds',
       'total_staffed_adult_icu_beds_coverage'], dtype=object)

In [12]:
summary = df.describe()['date'].apply(lambda x: x.date() if isinstance(x, pd.Timestamp) else x)

summary[['min','max']]

min    2020-01-01
max    2025-12-31
Name: date, dtype: object

In [13]:
df.head(10)

,date,state,fb-survey_smoothed_wwearing_mask_7d,fb-survey_smoothed_wcovid_vaccinated_appointment_or_accept,google-symptoms_sum_anosmia_ageusia_smoothed_search,fb-survey_smoothed_wcli,fb-survey_smoothed_whh_cmnty_cli,doctor-visits_smoothed_adj_cli,jhu-csse_confirmed_incidence_num,hhs_confirmed_admissions_covid_1d_prop_7dav,...,inpatient_beds_utilization,percent_of_inpatients_with_covid,inpatient_bed_covid_utilization,adult_icu_bed_covid_utilization,adult_icu_bed_utilization,cases_roll_7,day_of_year,day_of_week,month_of_year,quarter_of_year
0,2020-01-01,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,1,2,1,1
51,2020-01-02,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,2,3,1,1
102,2020-01-03,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,3,4,1,1
153,2020-01-04,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,4,5,1,1
204,2020-01-05,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,5,6,1,1
255,2020-01-06,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,6,0,1,1
306,2020-01-07,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,7,1,1,1
357,2020-01-08,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,8,2,1,1
408,2020-01-09,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,9,3,1,1
459,2020-01-10,AK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,10,4,1,1

In [16]:
print("Number of States Acquired:", len(df.state.unique()))

Number of States Acquired: 51

In [17]:
nas = df.isna().sum()
too_many_nas = nas[nas >= NA_THRESHOLD*len(df)]

assert len(too_many_nas) == 0, "Too many NA's for this feature to be useful."

## Download Data to Local

In [18]:
df.to_csv(f"data/covid_features_all_states_{START_DATE}_{END_DATE}.csv", index=False)